<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PlatformTarget>x64</PlatformTarget></PropertyGroup><ItemGroup><ProjectReference Include="../core/BD2Equipment.Core.csproj"/><ProjectReference Include="../connection/BD2Equipment.Connection.csproj"/><EmbeddedResource Include="cases.json" LogicalName="Tests.Cases.json"/></ItemGroup></Project>